notifications:
  email:
    recipients:
      - nacos_dev@linux.alibaba.com
      - dev-nacos@googlegroups.com
  on_success: change
  on_failure: always

language: java

jdk:
  - openjdk10
  - openjdk8

script: